"""
IMPORTANT: YOU HAVE TO RUN THIS IN A PYTHON IDE (like PyCharm) TO WORK!

-------------------------------
NUMBER GUESSING GAME
(A Beginner Python Project)
by Michael Cabrera
-------------------------------
https://github.com/thatpinkcoconut/NumberGuessingGame

Goal: The player guesses the number that is generated by the computer.
They will be given hints on how close their guesses are.

- The difficulty levels available are: Easy (from 1 to 20), Normal (from 1 to 50), and Hard (from 1 to 100).
- The number of attempts can be set to infinite, 3, 5, or 10.

For coders: I made it so that both of these parameters are customizable.
"""

import os
import random


def clear():
    os.system("cls" if os.name == "nt" else "clear")


# CONFIG
DIFFICULTYLEVELS_NAME = ("Easy", "Normal", "Hard")  # you can add more
DIFFICULTYLEVELS_MAXNUMBER = (20, 50, 100)  # you can add more
ATTEMPTLEVELS = ("infinite", 3, 5, 10)  # you can add more

# GLOBAL VARIABLES
number = 0
maxnumberindex = 0
attempts = 0
remainingattempts = 0
showattempts = True


def setdifficulty():
    global maxnumberindex

    clear()
    print("Set the difficulty of the game:")
    for i in range(len(DIFFICULTYLEVELS_NAME)):
        print("[{0}] - {1}".format(i, DIFFICULTYLEVELS_NAME[i]))

    while True:
        d = input()
        if d.isnumeric() and 0 <= int(d) < len(DIFFICULTYLEVELS_MAXNUMBER):
            maxnumberindex = int(d)
            break
        print("Invalid input. Try again.")


def setattempts():
    global attempts, remainingattempts, showattempts

    clear()
    print("Set the number of attempts:")
    for i in range(len(ATTEMPTLEVELS)):
        print("[{0}] - {1}".format(i, ATTEMPTLEVELS[i]))

    while True:
        a = input()
        if a.isnumeric() and 0 <= int(a) < len(ATTEMPTLEVELS):
            if int(a) == 0:
                attempts = 9999
                remainingattempts = attempts
                showattempts = False
            else:
                attempts = ATTEMPTLEVELS[int(a)]
                remainingattempts = attempts
                showattempts = True
            break
        print("Invalid input. Enter the number of your choice.")


def displayhud():
    print("|------------------------------------|")
    print("|      THE NUMBER GUESSING GAME!     |")
    print("|------------------------------------|")

    if showattempts:
        print("Difficulty: {0} \nAttempts left: {1}".
              format(DIFFICULTYLEVELS_NAME[maxnumberindex], remainingattempts))
    else:
        print("Difficulty: {0} \nAttempts left: Infinite".
              format(DIFFICULTYLEVELS_NAME[maxnumberindex]))

    print("--------------------------------------")


def generateNumber():
    global number
    number = random.randint(1, DIFFICULTYLEVELS_MAXNUMBER[maxnumberindex])


def game():
    global remainingattempts
    comment = ""

    setdifficulty()
    setattempts()
    generateNumber()

    clear()

    while remainingattempts > -1:
        clear()
        displayhud()

        print(comment) if comment != "" else None
        print("Guess the number from 1 to {0}!".format(DIFFICULTYLEVELS_MAXNUMBER[maxnumberindex]))
        g = input()
        if g.isnumeric():
            remainingattempts -= 1
            if int(g) == number:
                break
            elif int(g) > number:
                if abs(int(g) - number) <= 3:
                    comment = "You're very close! Lower!"
                else:
                    comment = "Lower!"
            elif int(g) < number:
                if abs(int(g) - number) <= 3:
                    comment = "You're very close! Higher!"
                else:
                    comment = "Higher!"
        else:
            print("Invalid input. Enter a number.")

    if remainingattempts <= -1:
        clear()
        print("You ran out of attempts. The correct number is {0}.".format(number))
        print("Better luck next time!")
    else:
        clear()
        print("You win! The correct number is {0}.".format(number))
        if showattempts:
            print("You did it in {0} attempts. Congratulations!".format(attempts - remainingattempts))

    print("\nInput [Y] to play again.")
    p = input()
    game() if p.upper() == "Y" else exit


if __name__ == '__main__':
    game()
