"""
NUMBER GUESSING GAME
(A Beginner Python Project)
by Michael Cabrera
-------------------------------

Goal: The player guesses the number that is generated by the computer.
They will be given hints on how close their guesses are.

- The difficulty levels available are: Easy (from 1 to 20), Normal (from 1 to 50), and Hard (from 1 to 100).
- The number of attempts can be set to infinite, 3, 5, or 10.
- These parameters are customizable, meaning the difficulty levels and number of attempts can be changed or increased.
"""
import os
import random


def clear(): os.system("cls" if os.name == "nt" else "clear")


# CONFIG - You can add/modify
DIFFICULTYLEVELS = (
    ("Easy", 20),
    ("Normal", 50),
    ("Hard", 100)
)
ATTEMPTLEVELS = ("infinite", 3, 5, 10)  # you can add more


def initgame():
    # Level of difficulty
    clear()
    print("Set the difficulty of the game:")
    for i in range(len(DIFFICULTYLEVELS)):
        print("[{0}] - {1}".format(i, DIFFICULTYLEVELS[i][0]))

    while True:
        d = input()
        if d.isnumeric() and 0 <= int(d) <= len(DIFFICULTYLEVELS[0]):
            difficulty = int(d)
            break
        print("Invalid input. Enter the number of your choice.")

    # No. of attempts
    clear()
    print("Set the number of attempts:")
    for i in range(len(ATTEMPTLEVELS)):
        print("[{0}] - {1}".format(i, ATTEMPTLEVELS[i]))

    while True:
        a = input()
        if a.isnumeric() and 0 <= int(a) < len(ATTEMPTLEVELS):
            if int(a) == 0:
                maxattempts = 9999
            else:
                maxattempts = ATTEMPTLEVELS[int(a)]
            break
        print("Invalid input. Enter the number of your choice.")

    # Finally, generate the number to guess
    the_number = random.randint(1, DIFFICULTYLEVELS[difficulty][1])

    return difficulty, maxattempts, the_number


def game():
    initvalues = initgame()
    difficulty = initvalues[0]
    maxattempts = initvalues[1]
    the_number = initvalues[2]
    _attempts = maxattempts
    _comment = ""

    def displayhud():
        print("|------------------------------------|")
        print("|      THE NUMBER GUESSING GAME!     |")
        print("|------------------------------------|")
        if maxattempts == "infinite":
            print("Difficulty: {0} \nAttempts left: Infinite".
                  format(DIFFICULTYLEVELS[difficulty][0]))
        else:
            print("Difficulty: {0} \nAttempts left: {1}".
                  format(DIFFICULTYLEVELS[difficulty][0], _attempts))
        print("--------------------------------------")

    while _attempts > 0:
        clear()
        displayhud()

        print(_comment) if _comment != "" else None
        print("Guess the number from 1 to {0}!".format(DIFFICULTYLEVELS[difficulty][1]))
        g = input()
        if g.isnumeric():
            _attempts -= 1
            if int(g) == the_number:
                break
            elif int(g) > the_number:
                if abs(int(g) - the_number) <= 3:
                    _comment = "You're very close! Lower!"
                else:
                    _comment = "Lower!"
            elif int(g) < the_number:
                if abs(int(g) - the_number) <= 3:
                    _comment = "You're very close! Higher!"
                else:
                    _comment = "Higher!"
        else:
            print("Invalid input. Enter a number.")

    if _attempts <= 0:
        clear()
        print("You ran out of attempts. The correct number is {0}.".format(the_number))
        print("Better luck next time!")
    else:
        clear()
        print("You win! The correct number is {0}.".format(the_number))
        print("You did it in {0} attempts. Congratulations!".format(maxattempts - _attempts))

    print("\nInput [Y] to play again.")
    p = input()
    game() if p.upper() == "Y" else exit


if __name__ == '__main__':
    game()
